BEGIN;


DROP TABLE IF EXISTS "tasks";

CREATE TABLE "tasks" (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name TEXT
);

INSERT INTO "tasks" (name) VALUES ('Faire les courses');
INSERT INTO "tasks" (name) VALUES ('Nourrir le chat');
INSERT INTO "tasks" (name) VALUES ('Aller au travail');


COMMIT;
